config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root 'home#index'

  get 'home' =>'home#index'
  get 'about' => 'pages#about'
  get 'd3plus'=> 'pages#d3plus'
  get 'iengine'=> 'pages#iengine'
  get 'imap'=> 'pages#imap'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def d3plus
  end

  def iengine
  end

  def imap
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/home/index.html.erb
<div class="row brand">
	<div class="col-md-2"></div>
		<div class="col-md-8">
			<span class="d3font">D3</span><br>Redefine Growth
		</div>
	<div class="col-md-2"></div>
</div>

app/views/layouts/_footer.html.erb
<!-- footer-->
<footer class="row" id="contact">
            <div class="col-md-4">&nbsp;</div>
            <div class="col-md-1">
                <a href="#"><img src="img/d3logo_white.png"width="100px"></a>
            </div>
            <div class="col-md-7" id="copyright">Copyright© 2011-2014 by D3. All rights reserved.</div>
</footer>

app/views/layouts/_navbar.html.erb
 <!--navigation -->
<div class="container-fluid">
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
         <!--  <a class="navbar-brand" href="home"><img src="img/d3logolong_white.png" /></a> --><!-- width="220" -->
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav" id="menu">
            <li><%= link_to "home",home_path%></li>
            <li><%= link_to "about",about_path%></li>
            <li><%= link_to "D3+",d3plus_path%></li>
            <li><%= link_to "impact engine",iengine_path%></li>
            <li><%= link_to "impact map",imap_path%></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>D3</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

   <%= render 'layouts/navbar' %>

   <% flash.each do |name, msg| %>
      <%= content_tag(:div,msg,class: "alert alert-info") %>
   <% end %>

  <div class="content">
    <%= yield %>
  </div>


   <%= render 'layouts/footer' %>


</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/d3plus.html.erb
<h1>Pages#d3plus</h1>
<p>Find me in app/views/pages/d3plus.html.erb</p>

app/views/pages/iengine.html.erb
<h1>Pages#iengine</h1>
<p>Find me in app/views/pages/iengine.html.erb</p>

app/views/pages/imap.html.erb
<h1>Pages#imap</h1>
<p>Find me in app/views/pages/imap.html.erb</p>